### ISSUE TITLE
Change Facebook page link in footer banner

### ISSUE THREAD

**Issue by cseas** [glugmvit/glugmvit.github.io#102]
Change Facebook link in the footer banner to: https://www.facebook.com/glugmvit/

**Comment by lkmandy** [comment]
Hi @cseas I'll like to work on this issue

**Comment by cseas** [comment]
Hi @lkmandy - Thanks for reaching out!
It appears someone already fixed the issue.
We'll be posting more beginner-friendly issues throughout October.

**Comment by lkmandy** [comment]
ok thanks, @cseas. I'll pick another issue
