### ISSUE TITLE
Footer text alignment for mobile screens

### ISSUE THREAD

**Issue by cseas** [glugmvit/glugmvit.github.io#46]
The footer text `Copyright © 2019 GLUG MVIT` gets left aligned on mobile screens and looks odd compared to the rest of the footer text which gets centre aligned.

This is because a `float-left` bootstrap class has been used on the text to keep it aligned left for desktop screens.

*Suggestion*: Add a css media query to [custom.scss](https://github.com/glugmvit/glugmvit.github.io/blob/master/assets/css/custom.scss) to fix the footer text alignment on mobile screens.

**Comment by asprazz** [comment]
I would like to work on this issue :)
