### ISSUE TITLE
Fix twitter authors icon

### ISSUE THREAD

**Issue by VictorBSI** [glugmvit/glugmvit.github.io#53]
**The Twitter authors icon doesn't appear correctly:**

![Twitter_issue_icon](https://user-images.githubusercontent.com/38796125/60391328-2533de80-9ac2-11e9-80cc-62c85dfa78a0.png)

**It should be something like this:**

![Twitter_icon](https://user-images.githubusercontent.com/38796125/60391346-cfac0180-9ac2-11e9-8014-61244b6ffe98.png)

**Browser:** Google Chrome 75.0.3770.100
**OS:** Windows 10 Pro

**Comment by cseas** [comment]
Referenced page containing the bug: https://blog.glugmvit.com/authors

*Suggestion for fix*: This is probably caused due to version issues in [https://fontawesome.com/]. Just changing the code to a twitter icon code compatible with the FontAwesome version used in the project should fix the bug.

**Comment by cseas** [comment]
Fixed by #105
